name: Cherry-Pick Hardcoded Commits

on:
  workflow_dispatch: 

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo
        uses: actions/checkout@v4
        with:
          ref: A8XX             
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch donor repo and cherry-pick
        run: |
          # Подключаем репозиторий whitebelyash
          git remote add donor https://github.com/whitebelyash/mesa-unified
          git fetch donor turnip/gen8

          # Запуск cherry-pick для ваших коммитов
          echo "Переносим коммиты..."b060b38
          git cherry-pick f42749e 65d70a9 f9a0cd3 f3f54cd 5c6f531 ba8b9f9 7ba1ad2 9b5e5f7 4fa5178
          c86f0ed 3e993e3 a8dd4aa 46cd5c4 f627470 eb273fb 4ab714b 70ec0ba
      - name: Push changes
        run: git push origin HEAD:A8XX
        
